### ISSUE TITLE
Which R2 implementations will use an internal web server?

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium-2#12]
Info given by D.Weck: 
R1 in native "launchers" use HTTP server for all EPUB resources, although historically there was an attempt to only serve audio/video via HTTP (the rest was fed into the WebView using custom URL protocol handler). Since WKwebview, even the top-level reader.html + JS etc. are served via HTTP (used to be file:// app-bundle)
But R1 in Chrome app and Electron and Apache Cordova etc. do not use HTTP server. 

Now that we are talking about developing more "per platform" native modules, in which case will we use a HTTP server and in which case will we use custom protocols?

**Comment by HadrienGardeur** [comment]
Well, I think the questions we need to ask also go beyond the use of an HTTP server, here are a few:

- HTTP 1.1 ? HTTP 2.0 with server push ?
- What is being served using HTTP ? A full app (reader.html + JS) ? A manifest through which I can access directly other resources and extract metadata ? Both ?
- Will the HTTP server listen too and support specific interactions ? For example, could I send a search request that would return a response document with locators ?

**Comment by HadrienGardeur** [comment]
FYI here's my position on these different points.

**1. Should we use an HTTP server in general?**

I think that we've proved that this is either useful or necessary in general and I like the consistency that this brings, both across platforms, but also between EPUB and PWP/BFF.

If we maximize our use of HTTP, I believe that we can build things in a way where supporting EPUB or PWP/BFF is essentially one and the same.

**2. HTTP version**

As it's been reported in Readium 1 before, there are clear benefits in using HTTP specific features to improve performance such as ETag/Last-Modified/Cache-Control.
I believe that HTTP/2 could also bring a number of improvements, for example it's fairly easy to use server push in order to:

- push the reader + JS when you first open the publication
- push the next document in the spine

While HTTP/2 is still gradually rolling out everywhere, we should still keep this in mind and make sure that we can leverage its features in the future.

**3. Serving content**

Ideally, I'd like each implementation to support the following things:

- expose a manifest in a format where a single document can contain all the information that we'll need (this covers metadata, spine, manifest and table of contents), which means that I can do a single request and cache it
- serve each resource in the publication in a way that doesn't require to rewrite links and URIs for images/audio/video/CSS/JS, which means that all paths will be relative to the manifest
- allow the ability to inject JS/CSS in HTML documents without using an iframe and injecting in JS (for example using query parameter such as `GET /chapter1.html?js=paginate.js&css=paginate.css` instead of a plain `GET /chapter1.html`) and expose this ability via a URI template in the manifest
- support media fragments, for example when I need to start audio/video at a specific timestamp
- serve a number of static resources that are useful (HTML reader, JS, CSS)

With all these, I think it would provide a lot of flexibility in what could be achieved by implementers:

- Reading System A can use the default implementation (currently reader.html + iframe)
- Reading System B decides instead that it would prefer to simply use our native implementation with its HTTP server + decryption, get the manifest (and cache it) and handle pagination and the rest itself (for example using the WKWebview APIs for pagination)
- Reading System C only streams EPUB files, and handles the HTTP part on their own server, but uses our JS to handle everything else in a native app with a Webview

**4. Interactions**

As much as possible, I'd like to make a number of interactions:

- discoverable in the manifest (links)
- available in HTTP

For example, a search endpoint for the current publication could be exposed in the manifest using:
`{"rel": "search", "href": "/search?q={searchTerms}", "type": "application/json", "templated": true}`

This would return a collection of locators with all the useful information to display to the user and navigate to the right place in the publication.

The best thing about this design is that it works for all three use cases that I've listed above in the previous section.

Not all interactions can be exposed that way, but for example search and fuzzy locators (where I'm trying to anchor back annotations but the document has been updated) are two very good examples.

**Comment by BigBlueHat** [comment]
Somewhat related--and at least worth pondering on--is the new discovery mechanism for ServiceWorkers: https://w3c.github.io/ServiceWorker/#example-00a7acb9

Once this is shipped it will be possible to reference a ServiceWorker installer from *any* response format--not just HTML.

It looks like this:
```http
Link: </reader-installer.js>;rel="serviceworker";scopy="/books/{isbn}"
```
and can be added to anything from an HTML page, an image/cover of the book, or even a Markdown/CommonMark intro page/document, or a the URL for a manifest.json (aka...it doesn't matter, the ServiceWorker would be discovered and get to do it's thing within the defined scope--which in Readium's case is kick off the reader).

Cool, right? :smile:

**Comment by rkwright** [comment]
Yes, and Hadrien's proposed design is very interesting.  One item to bear in mind, though, is that with the CloudReader you can't assume the latest browser will be used.  This doesn't mean that isn't feasible to go this route, only that the CloudReader will require something different and/or additional.  But it seems like the CloudReader will be a different code-base anyway.

**Comment by dmitrym0** [comment]
As a data point, it was very difficult to get iOS media playback right (especially when media was large) without `Content-Range` and friends so an HTTP server was a requirement for media assets.

**Comment by HadrienGardeur** [comment]
Overall there seems to be a broad consensus around the benefit of using an HTTP server.

The main concern remains security, new issues will be created by @rkwright specifically about that.

Now that we agree on HTTP, we'll need to define exactly what will be exposed and how. It's also worth exploring how performance can be improved using caching (ETags, Cache-Control) or push (HTTP/2).

**Comment by clebeaupin** [comment]
@HadrienGardeur We agree about using the HTTP protocol but we have not answer to the initial question that is "using or not an internal web server ?".

Using internal http servers on android or iOS apps make sense because these apps are running in sandboxes. You can run an HTTP server without having special permissions and you can make sure there will be no port conflicts.

On desktop, it's a little bit different: applications do not yet run in sandboxes. You could have port conflicts and moreover you could access your http server from external using a simple browser (security issue). It's why electron, for example, uses a different approach to server HTTP by registering HTTP protocol instead of launching an internal HTTP server.

**Comment by BigBlueHat** [comment]
Just gonna leave this right here... https://flyweb.github.io/ :smile:
