### ISSUE TITLE
What scripting language should be used?

### ISSUE THREAD

**Issue by rkwright** [readium/readium-2#3]
#### This is a Discussion

Some flavor of Ecmascript (e.g. 2016) or a fully-typed language such as TypeScript?
If so, which “typed script” language?

**Comment by llemeurfr** [comment]
We've heard a lot about TypeScript, which seems to have the lead currently.

**Comment by johanpoirier** [comment]
I prefer Ecmascript 2015 as it will be standard very soon.
Choosing a "type script" language will prevent readium from having contributions IMO.

**Comment by olivierkorner** [comment]
TypeScript looks great as it allows for better API definition as well as better class support and type checking that would benefit the code robustness.
I have a few concerns/questions though:
- I wonder though how it integrates with existing Javascript code and libraries.
- It makes the build process, which is already quite complex, even more so.
- How do you debug TypeScript?

**Comment by BigBlueHat** [comment]
Future JavaScript's like Ecmascript 2015 is one thing--as eventually it'll be native...or that's the plan and the build kit (babel, etc) which is necessary now is "temporary."

TypeScript, etc, are great for what they are, but will certainly narrow the number of potential contributors--just as CoffeScript did "back in the day."

Unless the strongly typed nature of TypeScript (etc) is a MUST for what's being built here (and it doesn't seem to be afaict), then I'd stick with ES2015 or "vanilla" JavaScript.

Keep the doors to the collaboration as wide open as possible.

**Comment by JCCR** [comment]
I'm happy with using at least ES2015.

But I think TypeScript would provide some nice benefits, such as the points made by @olivierkorner 
It solidifies the contracts that are defined, and more of the code is self documenting.

If we want to open the doors to collaboration we must be ready to accept the increased level of collaboration.
Before I felt like we had some barriers that prevented us from accepting pull requests from new contributors.
I asked myself: What impact will this new code make on the rest of the codebase? Will it introduce new subtle "hard to spot/hard to catch" bugs? could typing have helped with that? Is it this way because we don't have tests? Can typing make the code-review process easier or less overhead with analyzing code?

My point then would be if we don't choose to go with TypeScript then let's plan for having testing in place, with good enough coverage.

**Comment by HadrienGardeur** [comment]
I don't think that's an either/or scenario: no matter which technology is selected, TDD and good test coverage will make a massive difference.

A typed language is not in any way a good replacements for proper testing.

**Comment by JCCR** [comment]
@HadrienGardeur Yes of course! It isn't! I now see how my response looks like :) 
I made it sound like an either/or, but that's probably how it felt to me before with the way things were done and with our available resources. If we were to go back in time to when R1 was being architected and we chose to have TypeScript over vanilla JS, but we didn't have TDD in place.. I feel like going with TypeScript would have a difference

**Comment by danielweck** [comment]
http://stateofjs.com/2016/introduction/#sections

**Comment by iherman** [comment]
I think it is important to make it sure that a large developers' community could/should contribute via scripting. Whether we like it or not, the language being used these days is ECMAScript; any other language would greatly restrict the number of developers who would even be interested in contributing to Readium.

But... isn't that interpreter already part of the browser core natively? Why would it be necessary to think about anything else in the first place?

**Comment by rkwright** [comment]
I'm  in agreement with Ivan.  I understand that others want to go to a more structured, typed language, but it seems to me _(confession: not an expert)_ that ES6 offers a lot of that "for free".  See [here](https://github.com/lukehoban/es6features) and [here](http://es6-features.org/#Constants) 
My concern over TypeScript etc. is 

1. We impose a hurdle to participation by the developer community who may either not know TypeScript (for example) or don't like the chose language, don't like transpilers, etc.  We maximize our chance of getting help and participation by using the most commonly known tools.  Bear in mind that this is a project that (in all likelihood) won't be launched until late 2017 so support for ES6 will be even more widespread by then.
2. We impose a tooling step in our workflow by requiring a transpiler.  The transpiler may be really good and free of bugs (ha) but it IS an additional step.  Again, this seems to raise an additional barrier to wider participation.  Also, what about debugging in the browser? Or in a hybrid app?  Seems like an additional barrier that makes our task more difficult without a tremendous payback.
3. We risk obsolescence.  ES6 is mainstream and becoming more so.  It won't be replaced by the latest flavor of month during probable lifetime of Readium-2.  The same cannot be assured for TypeScript, etc.  Remember CoffeeScript.

**Comment by BigBlueHat** [comment]
Seems there's a trend in these posts toward ES6. Here's a handy resource as we look toward the near-term future:
http://kangax.github.io/compat-table/es6/

**Comment by danielweck** [comment]
TypeScript 2 is ECMAScript 6 (2015) with added type checking. This obviously means transpiling, but bear in mind that even when ES6 is implemented in all modern web browsers, toolchains / builds systems like Babel will probably still be used to generate "proper" distributable application bundles out of raw source code (and maybe to provide optimized module loaders too). PS: CoffeeScript ; unlike TypeScript ; had a very different programming language syntax than vanilla Javascript ES5. Also, TypeScript has traction in major projects such as AngularJS, and it supports ReactJS too. In fact, TS seems to have more traction than ES6!
Now, even though I can see functional areas in ReadiumJS that would benefit from a type system (handy "static" compile-time checking), I'd be happy to go for ES6 syntax (including modules), and a Babel build / debug workflow.
I totally agree with prioritizing test-driven development / comprehensive test coverage. This is the number one prerogative to achieve the level of quality Readium-2 needs.

**Comment by BigBlueHat** [comment]
@danielweck "TS seems to have more traction than ES6!" Can you validate that?

The little evidence I've found concerning popularity points the other way: http://stateofjs.com/2016/flavors/

**Comment by danielweck** [comment]
I am not aware of rigorous metrics to base any "ES6 vs. TypeScript" argument upon, thus why I said "seems to" ;)
Just out of interest though: https://www.google.com/trends/explore?date=all&q=typescript,es6

At any rate, the TypeScript workflow (type-checker + transpiler) means that ; functionally-speaking ; TypeScript is a superset of ES6. TS syntax adds type definitions over vanilla ES6. TS does not require the entire codebase to be fully-typed, and type inference / heuristics are used wherever possible. TS can in fact output ES6 instead of ES5, which means that Babel (and all its useful plugins) can be used as part of the debug / build workflow.

PS: I should stop saying ES6, it's ECMAScript 2015 ;)

**Comment by iherman** [comment]
> On 7 Oct 2016, at 21:46, Daniel Weck <notifications@github.com> wrote:
> 
> I am not aware of rigorous metrics to base any "ES6 vs. TypeScript" argument upon, thus why I said "seems to" ;)
> Just out of interest though: https://www.google.com/trends/explore?date=all&q=typescript,es6 <https://www.google.com/trends/explore?date=all&q=typescript,es6>
> At any rate, the TypeScript workflow (type-checker + transpiler) means that ; functionally-speaking ; TypeScript is a superset of ES6. TS syntax adds type definitions over vanilla ES6. TS does not require the entire codebase to be fully-typed, and type inference / heuristics are used wherever possible. TS can in fact output ES6 instead of ES5, which means that Babel (and all its useful plugins) can be used as part of the debug / build workflow.
> 
> PS: I should stop saying ES6, it's ECMAScript 2015 ;)
> 


I simply refer to it as JavaScript:-)

More to the point: if TS is a layer on top of JS, and if it can be converted into TS, then why would Readium even deal with it? If a developer wants to use TS, that is fine, he/she can produce the JS and go on. It is the same as for any browser; why do we have to deal with it in the first place?

**Comment by danielweck** [comment]
@iherman although unit tests and documentation are number one priorities, type "annotations" would help make the code more readable (better self-explanatory APIs), would enable safe refactoring workflows (currently regexp text search -based), would provide reliable auto-completion on most IDEs / editors, etc. ... and with TypeScript as a type-checker + transpiler tool (i.e. not a framework, just a small part of the build system) vanilla ES6/2015 would be supported too. Plus, many major libs now have type definitions available to help integrate non-TS code.

**Comment by clebeaupin** [comment]
Typescript +1

Typescript is just a superset of JavaScript and adds some great features:
- interfaces
- full-typed language
- mixins
- generics

Readium 2 is interface centric and shoud be implemented in different languages. In javascript world, ES6 does not provide interfaces but Typescript does.

Because typescript is full-typed language, type errors can be detected by the compiler so they never happen during the javascript runtime. In ES6 you have to write unit tests to test all the input types and return types of your methods, functions, so you add a lot of useless work. 
Moreover on a fully typed language, code is clearer, ide autocompletion works and built basic documentation is better. On ES6 you must add extra annotation on each var.

Mixins and generics are very useful when you want to develop a clear code: you can reduce the size of your code and make it reusable.

**Comment by rkwright** [comment]
@clebeaupin (and others) Out of curiosity, what tooling do you use with TypeScript?  What is the workflow?  How does one debug? Just normal JavaScript debugger? Obviously, I'm digging into it, but thought I would pick the brains of those with far more experience. I'm just a "1" at this point.

_(1:read about it, 2:hobby development, 3:developed production code, 4:guru)_

**Comment by danielweck** [comment]
@rkwright 

The NPM TypeScript CLI:
https://www.npmjs.com/package/typescript
(to compile TS source code into vanilla ES5/6)

VisualStudio *Code* (not to be mistaken with Microsoft VisualStudio!):
https://code.visualstudio.com/docs/languages/typescript
(this is an Electron-based cross-platform editor, with built-in syntax highlighting, "smart" code completion, refactoring, etc. (extensible via many plugins))

More information here (good intro video too, check it out ;) ):
https://www.typescriptlang.org/index.html#download-links

**Comment by clebeaupin** [comment]
I am using Visual Studio Code (https://code.visualstudio.com). This is, from far the best text editor, I have ever tested :-) 
Because it's Microsoft, Typescript integration is very good.

**Comment by danielweck** [comment]
PS (to my message above): debugging is done via sourcemaps (as usual) which are generated by the TypeScript compiler (option via CLI, or in `tsconfig.json`).
Although you can debug (breakpoint, introspect, etc.) the sourcemapped source tree directly from within the Chrome web inspector / debugger, you can also leverage the Chrome debugging protocol to debug directly from within VSCode, see: https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome

**Comment by danielweck** [comment]
FYI: `readium-js-viewer` actually includes a working VisualStudio Code config for debugging via the Chrome protocol: https://github.com/readium/readium-js-viewer/tree/develop/.vscode

**Comment by danielweck** [comment]
@rkwright WebStorm (for which Readium has free licenses) supports TypeScript too (including debugging):
https://www.jetbrains.com/help/webstorm/2016.2/typescript-support.html

**Comment by rkwright** [comment]
@danielweck Yes, I use WebStorm a fair amount (mainly on my side projects with WebGL).  I just did a couple of little tutorials in WebStorm with TypeScript and it works very well.  Generates and uses the source-maps invisibly.  Very nice.  Thanks for the feedback, folks.

**Comment by danielweck** [comment]
Dedicated Google Doc: https://docs.google.com/document/d/1xAogI06MOS3QgmG4eyJr6qgkWfKBMysqtbiUYxkMYwc

**Comment by iherman** [comment]
Forgive me for my ignorance, but I actually realized I do not really understand the original issue. My question is: what is the target audience for the usage of Typescript?

1. If it is aimed at the developer of Readium, ie, if the idea is that developers of Readium would develop the main modules in Typescript, and then turn it into Javascript for deployment
2. Typescript is the preferred script _users_ of Readium would be advised to use, ie, when adding scripts to their EPUB for whatever they want they are advised to use Typescript (and then Readium would have to include a Typescript *piler to Javascript)

In my view, no. 2 has no chance of winning. People outside use Javascript, they expect Javascript, and actually they get Javascript with the core browser engine. They *may* use other languages for their own development, like Typescript, Closure, whatever, but that is their business and Readium  should not interfere with that.

If the issue is no. 1 then, frankly, it is more difficult for me to have an opinion, because I never contributed to Readium. It is, essentially, an internal decision of the developer team. There may be some issues, though, namely if you expect external contributors to contribute to the Readium code. I keep hearing about the tools on Microsoft, and I also see that the various documentations all try to move people towards Visual Studio & friends but it may not help me too much if I am a Linux or Mac user, for example (o.k., I have seen that there is a Typescript mode in Atom, but that is only one element). Usage of Typescript may become an obstacle for many...

**Comment by danielweck** [comment]
1, not 2

**Comment by iherman** [comment]
Great. That is what I was hoping for:-)

**Comment by danielweck** [comment]
Ivan, TypeScript is open-source and cross-platform. Microsoft Visual Studio *Code* is a very popular Electron-based cross-platform coding / debugging tool, with a large community / set of plugins. I know many decks who prefer it to Atom or Brackets (also hybrid native / webview apps)
I think you are confusing the "old Microsoft way" when everything was Windows-bound and closed source.

**Comment by danielweck** [comment]
s/decks/devs ;)

**Comment by iherman** [comment]
> On 13 Oct 2016, at 10:06, Daniel Weck <notifications@github.com> wrote:
> 
> Ivan, TypeScript is open-source and cross-platform. Microsoft Visual Studio Code is a very popular Electron-based cross-platform coding / debugging tool, with a large community / set of plugins. I know many decks who prefer it to Atom or Brackets (also hybrid native / webview apps)
> I think you are confusing the "old Microsoft way" when everything was Windows-bound and closed source.
> 


O.k., I accept that. As i said, if this is really an "internal" developers' issue, then probably the best choice is what that group feels most comfortable with, and I cannot comment on that...

**Comment by danielweck** [comment]
"Sustaining webpack for the future"

"Support for taking the time to convert the entire project to TypeScript. We believe that TypeScript allows users to better write scaled and complex code with rich APIs "

https://medium.com/webpack/sustaining-webpack-for-the-future-part-1-32bea7f9e8a2#.ya7m9jqw7

**Comment by winniequinn** [comment]
I've put together a little TypeScript 2 project so anyone unfamiliar with TypeScript can see how to set things up and get started writing libraries: https://gist.github.com/winniequinn/c84cc60820f79b6eaebc725bc522dc39
