### ISSUE TITLE
Coordinating Releases and Versions Across Platforms

### ISSUE THREAD

**Issue by rkwright** [readium/readium-2#55]
The question here is how to coordinate:

- versions for different platforms
- how those versions correspond to features across platforms
- how and when sub-versions are incremented across platforms and how they relate to the first two items

Note that this discussion is different from issue #6  (How should versioning be implemented?) because this discussion is about coordination of that version across platforms.  At present, there are 4 different platforms in R2 (Go, iOS, Android and Desktop) with a fifth (Web) lurking.  Already, these platforms are significantly out of synch.
The question becomes do the version/labels (whatever they are) correspond to a point in time, or a set of features?

To be continued....

**Comment by rkwright** [comment]
Another variant of this is how versioning works even within a give platform, e.g. does the Streamer have the same version as the Navigator?  An easy answer is "just use Semantic Versioning", but IMO that doesn't really solve the problem.  

There are some interesting threads on Stackoverflow and other places about these issues:
https://gist.github.com/jashkenas/cbd2b088e20279ae2c8e
https://softwareengineering.stackexchange.com/questions/255742/is-it-correct-to-keep-version-numbers-of-all-components-always-the-same

I don't know what the right answer is. As another example, in my own [github org](https://github.com/rkwright) (which is littered with old projects) there are four related repos (sim_basin, sim_hurricane, nehe-three-js,  and gfx-common).  In gfx-common are a number of utils and libraries.  Currently, they all have their own (semantic) versions, which are currently different.  I've finally gotten around to thinking of doing a formal (github) release, but what version  does the release get?  The highest version among all of them?  Some sequential number that is special to the repo itself?

Here in Readium we have the same issue.  We release readium-1 periodically (just released 0.29).  This version is reflected in some of the components (js-viewer, Android-Launcher, iOS-Launcher and OSX-Launcher but NOT in the SDK or js-cfi.  This hasn't presented any problems that I know of, but  who knows?

As we start to think about "releasing" r2, the question comes up again?  How are the various components versioned?  Are the releases in concert (not likely, IMO)?  How to keep track of all this?

I don't have the answer to all this, but I think it needs to be discussed, soon.

**Comment by danielweck** [comment]
Regarding semantic versioning and branch / release management, here is how Electron does it:
https://electronjs.org/docs/tutorial/electron-versioning

**Comment by danielweck** [comment]
In Readium "1" (ReadiumJS + ReadiumSDK), because of precise submodule references ; which are hard-coded in the Git source tree as commit hash points ; the release-tagged head of the master branch for a top-level app project (e.g. `SDKLauncher-iOS`) resolves its Readium dependencies (i.e. submodules) as precise unique points in the commit history, as opposed to using a selection algorithm based on semantic versioning "ranges". In the context of Readium "1" it therefore makes sense to simplify the release process by unilaterally triggering a release (version update) in *all* repositories, even if there are no changes at all in some of these repositories / submodules / (sub)projects. For example: let's say that a major update in `readium-shared-js` justifies a version increment and corresponding official release (tagged in the master branch). As a consequence, the master branch of `SDKLauncher-Android` must now update its reference to the `readium-shared-js` submodule, anf formally-speaking this translates into create a release point in the commit history (identical to `readium-shared-js`), even though no code has actually changed in `SDKLauncher-Android`.

**Comment by danielweck** [comment]
In Readium "2" I would much prefer if each individual (sub)project ; such as "streamer", "navigator", etc. ; had its own semantic version. This way, let's say for example that a breaking change is introduced in "streamer" (denoted by an increment in the major field of the version string) => any software module that depends on "streamer" will *not* automatically inherit this changes, and will first have to adapt its code, then explicitly reference an incremented semantic versioning range. The advantage of separate versions for each R2 module is that a minor (non-breaking) update in a module requires no adaptation at all in modules that depend on it (other than a semi-automatic update of the NPM / YARN "lock" file for Javascript projects, as this is where precise version references are recorded in order to enable predictable / reproducible builds).

**Comment by HadrienGardeur** [comment]
I agree with Daniel that from a Readium-2 perspective, it makes a lot more
sense to have semantic versioning per project.

**Comment by llemeurfr** [comment]
Let's go this way, independent versions per module. This is starting on the iOS dev, with modules starting at V1.0.0.
