### ISSUE TITLE
How "modular" do we want Readium-2 to be?

### ISSUE THREAD

**Issue by rkwright** [readium/readium-2#8]
#### This is a Discussion
- What does it mean to be modular?
- Can the modules be written in different languages?
- Can the modules be used standalone?

**Comment by HadrienGardeur** [comment]
I think modular means that:

- each module are as independent from one another as possible
- when I "build" Readium SDK I should be able to pick and chose which module I'd like to use
- each module should have a standard API associated to it, which will let developers implement the module in whatever language they'd like best

**Comment by llemeurfr** [comment]
This is related to #1. One of the main tasks of the R2 architects will be to find the best modules and their interfaces, and allow modules to be written in different languages.
I don't foresee these modules to be used standalone (such a goal may makes things more difficult).

**Comment by danielweck** [comment]
@whmccoy said ( https://github.com/readium/readium-2/issues/4#issuecomment-253265043 ):

I agree with Fred but I would actually vote for an even more radical
modularization.

I think that we will need to be looking feature by feature at everything in
EPUB and seeing how those features can be used for website content as well
as packaged publications. By way of a long-standing example, there is no
reason not to be able to use Media Overlays on any website as a modular
feature. Significant format work will be needed to figure out how to do
these things modularly (it's easy to say let's make Media Overlays work for
websites but you don't want to pull in OPF to do so so you need to at a
minimum invent some "link rel=" or other means to designate it). And I'm
not sure that this format work will ripen in the timeframe for Readium 2.
But it might and I think R2 will be best set up for the future if we don't
think of it as monolithically supporting a monolithic format but as
modularly supporting a set of modular features (that just happened to all
be balled up together in today's EPUB 3) with a set of polyfills that can
be used separately when appropriate.

Another example is navigation. To me there is no reason that JS code that
finds a <nav> element with id=toc and processes it into a convenient
machine-readable format and provides a nice UX affordance should have to
know anything about the rest of EPUB 3. Any website should be able to
designate a "toc nav" and be able to use as a polyfill such nav code.

Dynamic loading of MathJAX to support MathML is another example of what IMO
should be a separate polyfill.

And pagination. We don't paginate across content documents only within
them. So why not treat our pagination code as a modular polyfill that can
be used on any website that wants to offer a paginated view (and perhaps
literally a polyfill by implementing overflow=page or whatever).

I would therefore make it a requirement that the R2 support in JS for any
given feature MUST be usable on a standalone basis and therefore MUST NOT
know about any other feature. If we discover that there are subcomponents
that need to be used by more than one R2 feature then those are shared
supporting libraries/dependencies (we don't want to be loading 5 copies of
backbone.js because 5 R2 feature polyfills use backbone.js but that is a
normal issue in developing JS web apps).

Again this is kind of a radical idea and I'm not suggesting it's the only
way to go but I do think that the technical team should seriously consider
it and its implications given the likely future directions at the format
level.

--Bill

**Comment by danielweck** [comment]
@fchasen and @danielweck to boostrap document (Google Doc)

**Comment by danielweck** [comment]
Here ya go: https://docs.google.com/document/d/1DFCwH4Wm5_QP5X-14e-9mJ5EY_llncp1FuWO6K3lNLQ

**Comment by winniequinn** [comment]
I've done some more thinking about this, and I feel like we really need to distinguish between _libraries_ and _plugins_. 

During the course of development, it is definitely going to make sense to break out parts of code into libraries. Libraries are reusable, independently testable, and easy to develop in parallel with other parts of the code, and those are all good things! I don't think anyone would dispute that.

I see plugins, however, as something different. While libraries are generally compile-time dependencies that always included, plugins are dynamically loaded components that are included based upon the desired configuration. They share all of the advantages of what I'm calling libraries, but on top of that they add flexibility and complexity.

To put it another way, an application built upon tons of libraries may still have only one possible configuration, but an application built on top of a series of N plugins that can either be included or not included has 2^N possible configurations. While it's definitely possible to clearly define interfaces and isolate components and all of that so you don't have exponential complexity in practice, you still have, at a minimum, the additional design work that goes into defining all of the general interfaces to which various plugins can confirm and the additional testing effort that goes into ensuring all possible combinations work as intended.

My general impulse is to break things out into libraries as much as possible, but also to _avoid_ plugin architectures as much as possible. There are a few cases where such things are absolutely going to be needed, but I would err on the side of simplicity and uniformity wherever we can.

**Comment by whmccoy** [comment]
I think the classic application taxonomy in re: libraries vs. plugins
doesn't necessarily make 100% sense in our situation since R2 at least in
JS layer will, like R1, necessarily be extending a Web browser engine and
its main job involves processing Web content (HTML,CSS,SVG,etc.). I.e. we
are plugging in dynamically to an existing app (the browser runtime) so
whether R2 is one monolithic plugin or several independent ones it is not
per se its own separate app. I think that needs to inform architectural
thinking about how it should be structured.

--Bill
On Oct 12, 2016 4:06 PM, "Winnie Quinn" <notifications@github.com> wrote:

I've done some more thinking about this, and I feel like we really need to
distinguish between *libraries* and *plugins*.

During the course of development, it is definitely going to make sense to
break out parts of code into libraries. Libraries are reusable,
independently testable, and easy to develop in parallel with other parts of
the code, and those are all good things! I don't think anyone would dispute
that.

I see plugins, however, as something different. While libraries are
generally compile-time dependencies that always included, plugins are
dynamically loaded components that are included based upon the desired
configuration. They share all of the advantages of what I'm calling
libraries, but on top of that they add flexibility and complexity.

To put it another way, an application built upon tons of libraries may
still have only one possible configuration, but an application built on top
of a series of N plugins that can either be included or not included has
2^N possible configurations. While it's definitely possible to clearly
define interfaces and isolate components and all of that so you don't have
exponential complexity in practice, you still have, at a minimum, the
additional design work that goes into defining all of the general
interfaces to which various plugins can confirm and the additional testing
effort that goes into ensuring all possible combinations work as intended.

My general impulse is to break things out into libraries as much as
possible, but also to *avoid* plugin architectures as much as possible.
There are a few cases where such things are absolutely going to be needed,
but I would err on the side of simplicity and uniformity wherever we can.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/readium/readium-2/issues/8#issuecomment-253365276>, or mute
the thread

**Comment by fchasen** [comment]
As @winniequinn pointed out, modules can be broken into several different types:

**Libraries** for specific tasks, broken up into javascript modules to ease simultaneous development, testing, refactoring, different platform code ect. These might be to internal projects or external but may not be useful on their own. 

- Parsing OPF
- ToC
- Navigation
- Search

**Plugins**, functionality that might be implemented by users in many different ways depending on the use case. I think of these as responding to events (like selection) and overridable functions (like requesting files) of the main library / ui.

- External Search
- Annotations
- File Loading / Storage
- Image Viewer

**Polyfills**, functionality that extends the browser and could be used by PWP and others

- Pagination strategy
- Highlight layer
- Locating a specific place in text (CFI, Xpath..)
- Media Overlays
- Styling Themes (night mode)
- Text resize / reflow events

I’d hope as much of the rendering as possible will fall into the polyfill category, but that will certainly add complexity to architecting and organizing their development.

On the reader logic / ui side it think PDF.js is a good example to follow with a basic rendering api, simple viewer examples and a full-fledged reader built on top of those.

**Comment by dmitrym0** [comment]
Is there any generic plugin or component module theory out there? I'm trying to understand how all of these pieces would fit together, so far all I've found is [OSGI](https://en.wikipedia.org/wiki/OSGi). It's quite meaty.
